### ISSUE TITLE
Sobre o Evento Realizado do dia 6

### ISSUE THREAD

**Issue by Jacintomuambumba** [angolaosc/aosf-website#30]
É bem sabido que o evento do dia 6 já passou, que tal adicionar uma informação para mostrar aos usuários que o evento já passou?

![image](https://github.com/angolaosc/aosf-website/assets/85085174/b56ee454-5faf-407c-9711-d62d2c2d451b)

pretendo fazr isso,  porque pode confundir as pessoas que acederem o site, por exemplo eu, achei que ainda estava em pé.

**Comment by antonio-pedro99** [comment]
Obrigado pela sugestão @Jacintomuambumba.
Essa issue está sendo resolvido pela #31

**Comment by Jacintomuambumba** [comment]
Estou trabalhando nesta issues para, infirmar que os events do dia 6 já foram realizados, 

Team CoDev

**Comment by Jacintomuambumba** [comment]
Boa Noite Antonio, Podes adicionar a etiqueta hacktoberfest nesta issue?
