### ISSUE TITLE
Internacionalização do Website

### ISSUE THREAD

**Issue by trupakufi** [angolaosc/aosf-website#37]
Adicionar Suporte para tradução de português para inglês e vice-versa.

**Comment by antonio-pedro99** [comment]
Olá @trupakufi, muito obrigado pela sugestão. 
Mas eu nāo acho que precisamos dessa funcionalidade agora. O AOSFest terminará já esta semana.

**Comment by trupakufi** [comment]
@antonio-pedro99 Perfeito, e o outro site precisa ou já tem ? Acabei de ver que tem até demasiado.

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 Perfeito, e o outro site precisa ou já tem ? Acabei de ver que tem até demasiado.

Já tem :)
