### ISSUE TITLE
Eventos passados

### ISSUE THREAD

**Issue by Jacintomuambumba** [angolaosc/aosf-website#39]
É bem sabido que o evento do dia 24 já passou, que tal adicionar uma informação para mostrar aos usuários que o evento já passou?

**Comment by antonio-pedro99** [comment]
> É bem sabido que o evento do dia 24 já passou, que tal adicionar uma informação para mostrar aos usuários que o evento já passou?

E vc nem participou do evento :)

**Comment by antonio-pedro99** [comment]
> É bem sabido que o evento do dia 24 já passou, que tal adicionar uma informação para mostrar aos usuários que o evento já passou?

Don't worry, vamos mudar em breve!

**Comment by Jacintomuambumba** [comment]
Não participei porque estudamos de noite, estavamos em Aulas
